akorn_admin/apps/backend/urls.py
from django.conf.urls.defaults import patterns, include, url
import views

urlpatterns = patterns('',
    url(r'^backend/journals$', views.backend_journals, name='backend_journals'),
    url(r'^backend/journals/(?P<journal_id>.*)$', views.backend_journal, name='backend_journal'),
    url(r'^backend/scrapers$', views.backend_scrapers, name='backend_scrapers'),
)

akorn_admin/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'admin.views.home', name='home'),
    # url(r'^admin/', include('admin.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'', include('apps.backend.urls', namespace='backend')),

	url(r'^'+settings.STATIC_URL[1:]+'(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.STATIC_ROOT}),
)

akorn_admin/apps/backend/models.py
from django.db import models

# Create your models here.

akorn_admin/apps/backend/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.template import RequestContext
from akorn.couch import db_store, db_journals
from akorn.celery.scrapers import tasks

def backend_journals(request):
  db_docs = db_store
  
  journals = [db_journals[doc_id] for doc_id in db_journals if '_design' not in doc_id]

  journals = sorted(journals, key=lambda doc: doc['name'])

  for journal in journals:
    journal.num_docs = len(db_docs.view('index/journal_id', key=journal.id, include_docs=False).rows)

  return render_to_response('backend/journals.html', {'journals': journals,}, context_instance=RequestContext(request))

def backend_journal(request, journal_id):
  db_docs = db_store 
  journal_doc = db_journals[journal_id]

  rows = db_docs.view('index/journal_id', key=journal_id, include_docs=True).rows

  num_rescrape = 0
  scraper_modules = set()
  
  docs = [row.doc for row in rows]

  for row in rows:
    doc = row.doc
    if 'rescrape' in doc and doc['rescrape']:
      num_rescrape += 1
   
    if 'scraper_module' in doc:
      scraper_modules.add(doc['scraper_module'])

  return render_to_response('backend/journal.html', {'journal': journal_doc,
                                                     'docs': docs,
                                                     'num_rescrape': num_rescrape,
                                                     'scraper_modules': list(scraper_modules),},
                            context_instance=RequestContext(request))

def rescrape_doc(doc_id):
  doc = db_store[doc_id]

  doc['currently_rescraping'] = True
  db_store.save(doc)

  if 'source_url' in doc:
    print doc['source_url']
    tasks.scrape_journal.delay(doc['source_url'], doc.id)
  elif 'source_urls' in doc:
    print doc['source_urls']
    tasks.scrape_journal.delay(doc['source_urls'][0], doc.id)
  elif 'scraper_source' in doc:
    print doc['scraper_source']
    tasks.scrape_journal.delay(doc['scraper_source'], doc.id)

def backend_scrapers(request):
  if request.method == "POST":
    docs_to_rescrape = [b for a in request.POST.getlist('to_rescrape') for b in a.split(',')]
    
    for doc in docs_to_rescrape:
      rescrape_doc(doc)

  in_progress = {'num': 0}
  for row in db_store.view('rescrape/currently_rescraping', group=True).rows:
    in_progress['num']=row['value']

  scraper_details = {}
  
  for row in db_store.view('rescrape/scraper_exception_errors').rows:
    module, error = row['key']
    error = error.split(":")[0]
    scraper_details.setdefault(module, 
                               { 'name': module.split('.')[-1],
                                 'module': module,
                                 'num_docs': 0,
                                 'errors': {}})
    scraper_details[module]['errors'].setdefault(error, {'num_rescrape': 0, 'ids':[]})
    scraper_details[module]['errors'][error]['num_rescrape'] += 1
    scraper_details[module]['errors'][error]['ids'].append(row['id'])
    
  for row in db_store.view('rescrape/scraper_total_docs', group=True):
    module = row['key']
    if module in scraper_details:
      scraper_details[module]['num_docs'] = row['value']

  scrapers = []
  for key, details in scraper_details.items():
    errors = []
    for exception, error_details in details['errors'].items():
      errors.append({'exception':exception, 
                     'num_rescrape':error_details['num_rescrape'], 
                       'ids':u",".join(error_details['ids']),})
      
    scrapers.append({'name':details['name'],
                     'module':details['module'],
                     'num_docs':details['num_docs'],
                     'error_type_count':len(details['errors']),
                     'errors': errors})

  return render_to_response( 'backend/scrapers.html', 
                             {'scrapers': scrapers,
                              'in_progress': in_progress,}, 
                             context_instance=RequestContext(request) )

akorn_admin/templates/backend/journal.html
{% extends 'page.html' %}

{% block scripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}search/js/json2.js"></script>
<script src="{{ STATIC_URL }}search/js/tag-it.js"></script>
<script src="{{ STATIC_URL }}search/js/main.js"></script>
{% if last_visit %}
<script type="text/javascript">
// TODO There is probably a better way to do this
akorn.last_visit = "{{ last_visit|date:"c" }}";
// When the document has loaded start the show
$(document).ready(akorn.init);
</script>
{% endif %}

<style>
  table.journals_table {

  }

  table.journals_table thead tr {
    text-align:center;
    border-bottom:1px solid #666;
  }

  tr.table-row td {
   margin:0.25em;
   padding:0.25em;
  }
  
  tr.table-row td ul {
    list-style:none;
    font-size:0.9em;
  }

  tr.table-row td {
    vertical-align:top;
  }

  tr.table-row-False {
    background:#F9F9F9;
  }
</style>
{% endblock %}

{% block content %}
<div class="span9 search">
  <h2>{{ journal.name }}</h3>
  <ul>
  {% for alias in journal.aliases %}
    <li>{{ alias }}</li>
  {% endfor %}
  </ul>
  <p>Total number of docs: {{ docs|length }}</p>
  <p>Number to rescrape: {{ num_rescrape }}</p>
  <p>Scrapers used:
    <ul>
      {{ scraper_journals }}
      {% for scraper in scraper_modules %}
        <li>{{ scraper }}</li>
      {% endfor %}
    </ul>
  </p>
  <p>
    <ul>
      <script>
        function toggle(doc_id) {
          $('#doc' + doc_id).toggle();
        }
      </script>
      {% for doc in docs %}
      <li><a onclick='toggle("{{ doc.id }}");'>{{ doc.id }}</a><br/>
        <table style='display:none;' id='doc{{ doc.id }}'>
        {% for key, val in doc.items %}
          <tr><td valign='top' style='font-weight:bold;'>{{ key }}</td><td valign='top'>{{ val }}</td></tr>
        {% endfor %}
        </table>
      </li>
      {% endfor %}
    </ul>
  </p>
</div>

<div class="span3">

</div>
{% endblock %}

akorn_admin/templates/backend/journals.html
{% extends 'page.html' %}

{% block scripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}search/js/json2.js"></script>
<script src="{{ STATIC_URL }}search/js/tag-it.js"></script>
<script src="{{ STATIC_URL }}search/js/main.js"></script>
{% if last_visit %}
<script type="text/javascript">
// TODO There is probably a better way to do this
akorn.last_visit = "{{ last_visit|date:"c" }}";
// When the document has loaded start the show
$(document).ready(akorn.init);
</script>
{% endif %}

<style>
  table.journals_table {

  }

  table.journals_table thead tr {
    text-align:center;
    border-bottom:1px solid #666;
  }

  tr.table-row td {
   margin:0.25em;
   padding:0.25em;
  }
  
  tr.table-row td ul {
    list-style:none;
    font-size:0.9em;
  }

  tr.table-row td {
    vertical-align:top;
  }

  tr.table-row-False {
    background:#F9F9F9;
  }
</style>
{% endblock %}

{% block content %}
<div class="span9 search">
  <h2>Journals summary</h2>
  <table class='journals_table'>
  <thead>
  <tr>
    <th></th><th>Name</th><th>Aliases</th><th>Num docs</th>
  </tr>
  </thead>
  {% for journal in journals %}
    <tr class="table-row table-row-{{ forloop.counter0|divisibleby:'2' }}">
      <td><input type='checkbox' value='{{ journal.id }}'/></td>
      <td><a href="{% url 'backend:backend_journal' journal_id=journal.id %}">{{ journal.name }}</a></td>
      <td>
        <ul>
          {% for alias in journal.aliases %}
          <li>{{ alias }}</li>
          {% endfor %}
        </ul>
      </td>
      <td>{{ journal.num_docs }}</td>
    </tr>
  {% endfor %}
  </table>
</div>

<div class="span3">

</div>
{% endblock %}

akorn_admin/templates/backend/rescrape.html
{% extends 'page.html' %}

{% block scripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}search/js/json2.js"></script>
<script src="{{ STATIC_URL }}search/js/tag-it.js"></script>
<script src="{{ STATIC_URL }}search/js/main.js"></script>
{% if last_visit %}
<script type="text/javascript">
// TODO There is probably a better way to do this
akorn.last_visit = "{{ last_visit|date:"c" }}";
// When the document has loaded start the show
$(document).ready(akorn.init);
</script>
{% endif %}

<style>
  table.scrapers_table {

  }

  table.scrapers_table thead tr {
    text-align:center;
    border-bottom:1px solid #666;
  }

  tr.table-row td {
   margin:0.25em;
   padding:0.25em;
  }
  
  tr.table-row td ul {
    list-style:none;
    font-size:0.9em;
  }

  tr.table-row td {
    vertical-align:top;
  }

</style>
{% endblock %}

{% block content %}
<div class="span9 search">
  <h2>Rescrape...</h2>
  <a href="/backend/scrapers">Scraper panel</a>
</div>

<div class="span3">

</div>
{% endblock %}

akorn_admin/templates/backend/scrapers.html
{% extends 'page.html' %}

{% block scripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}search/js/json2.js"></script>
<script src="{{ STATIC_URL }}search/js/tag-it.js"></script>
<script src="{{ STATIC_URL }}search/js/main.js"></script>
{% if last_visit %}
<script type="text/javascript">
// TODO There is probably a better way to do this
akorn.last_visit = "{{ last_visit|date:"c" }}";
// When the document has loaded start the show
$(document).ready(akorn.init);
</script>
{% endif %}

<style>
  table.scrapers_table {

  }

  table.scrapers_table thead tr {
    text-align:center;
    border-bottom:1px solid #666;
  }

  tr.table-row td {
   margin:0.25em;
   padding:0.25em;
  }
  
  tr.table-row td ul {
    list-style:none;
    font-size:0.9em;
  }

  tr.table-row td {
    vertical-align:top;
  }

</style>
{% endblock %}

{% block content %}
<div class="span9 search">
  <h2>Scraper summary</h2>
  <div>
    Currently rescraping: {{ in_progress.num }}.  <a href="/backend/scrapers">refresh</a>
  </div>
  <form method="post" action="/backend/scrapers">{% csrf_token %}
    <button>rescrape</button>
    <table class='scrapers_table'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Module</th>
          <th>Total docs</th>
          <th>Error</th>
          <th>Num to rescrape</th>
          <th></th>
        </tr>
      </thead>
      {% for scraper in scrapers %}
      {% for error in scraper.errors %}
      <tr class="table-row">
        {% if forloop.counter0 == 0%}
        <td rowspan="{{scraper.error_type_count}}">
          {{scraper.name}}
        </td>
        <td rowspan="{{scraper.error_type_count}}">
          {{scraper.module}}
        </td>
        <td rowspan="{{scraper.error_type_count}}">
          {{scraper.num_docs}}
        </td>
        {% endif %}
        <td>{{error.exception}}</td>
        <td>{{error.num_rescrape}}</td>
        <td>
          <input type='checkbox' name='to_rescrape' value='{{error.ids}}'/>
        </td>
      </tr>
      {% endfor %}
      {% endfor %}
    </table>
  </form>
</div>

<div class="span3">

</div>
{% endblock %}

akorn_admin/templates/page.html
<!DOCTYPE html>
<html lang="en"> 
    <head> 
        <meta charset="utf-8"> 
        <link rel="stylesheet" href="{{ STATIC_URL }}search/css/bootstrap.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}search/css/ui-lightness/jquery-ui-1.8.22.custom.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}search/css/grid.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}search/css/base.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}search/css/jquery.tagit.css">
        <title>Akorn {% block pagetitle %}open science{% endblock %}</title>
        {% block canonical %}{% endblock %}
        {% block og_meta %}{% endblock %}
    </head>
    <body>
        <div class="navbar">
            <div class="navbar-inner">
                <a class="brand" href="/">AKORN</a>
                <ul class="nav">
                    <li><a href="/about/">About</a></li>
                    <li><a href="http://blog.akorn.org/">Blog</a></li>
                </ul>
                <p class="lead pull-right">Research in a nut shell</p>
            </div>

        </div>

        {% block container %}
        <div id="content" class="container-fluid">
            <div class="row-fluid">
            {% block content %}
            {% endblock %}
            </div>
        </div>
        {% endblock %}
    {% block scripts %}
    <script src="{{ STATIC_URL }}search/js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}search/js/jquery.jsonp-2.4.0.min.js"></script>
    <script src="{{ STATIC_URL }}search/js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}search/js/jquery-ui-1.8.22.custom.js"></script>
    {% endblock %}
    </body>
</html>